### ISSUE TITLE
Chinese warlords

### ISSUE THREAD

**Issue by NotOddity** [NotOddity/hoi4-community#23]
ban people from going chinese war lords like gaunxi clique
from joning japan

- from wezdominator

**Comment by NotOddity** [comment]
"vs a a china player
as it it ruins a china players game and any chance of them wining
if the war starts in 37"

**Comment by Adamski2k** [comment]
Added to rule set.

**Comment by Adamski2k** [comment]
I changed your rule that war lords may only be played if China allows it.
